name: Test that the code is formatted properly

on:
  push:
    branches:
      - master
      - 2024-Competition-*
  pull_request: {}
  workflow_dispatch: {}

jobs:

  test-format:

    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting with spotless
        shell: bash
        run: bash gradlew spotlessCheck

