name: Test that the code will build

on:
  push:
    branches:
      - master
      - 2024-Competition-*
  pull_request: {}
  workflow_dispatch: {}

jobs:

  test-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: gradle build
        shell: bash
        run: bash gradlew build build --warning-mode all

      - name: gradle check
        shell: bash
        run: bash gradlew build check

      - name: gradle test
        shell: bash
        run: bash gradlew build test

